### ISSUE TITLE
docker-compose up -d fail

### ISSUE THREAD

**Issue by ghost** [Jamlee/docker-laravel#2]
ERROR: for web  Cannot start service web: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/088861f92eab200486b0ec3d9
rc" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/088861f92eab200486b0ec3d91cc3a398deaea910907364e5188d86e9389aed0" caused "not a directory"
[31mERROR[0m: Encountered errors while bringing up the project.

**Comment by Jamlee** [comment]
maybe need check docker-compose
